language: python
python:
- '3.7'
jobs:
  include:
  - stage: standalone
    name: Code Style + Unit Tests (standalone)
    before_install:
    - pip install pycodestyle
    - pip install pytest
    - pip install pytest-cov
    - pip install coveralls
    script:
    - find . -name \*.py -exec pycodestyle --exclude */res.py --max-line-length=120
      --ignore=E402 {} +
    - pytest --cov=tpRigToolkit
    after_success:
    - coveralls
  - stage: docs
    name: Build Documentation
    if: tag =~ ^releases/*
    before_install:
    - pip install sphinx
    - pip install sphinx_rtd_theme
    script:
    - sphinx-apidoc -f -e -o docs/sphinx tpDcc
    - sphinx-build -M html ./docs/sphinx ./
    after_success:
    - cd html && touch .nojekyll && cd ../
    deploy:
    - provider: pages
      skip_cleanup: true
      github_token: "$GITHUB_TOKEN"
      keep_history: true
      local_dir: html
      on:
        branch: main
        tags: true
  - stage: deploy
    name: Deploy
    if: tag =~ ^releases/*
    script: skip
    deploy:
    - provider: pypi
      skip_cleanup: true
      user: tpoveda
      password:
        secure: OYFF1JJT2x4QE9NU+xVNxBJMNYEsaMEnuM3JBQlvU/JFpid6aYPjbGC/kFICBWz8QCBMKvmyy01sa5SpFJ4Em/7+T+aeXS9qGLFVciH9AcwyJQlrzjNJxF2T7+iGKXgszc4h0qXZJ4w1RZuykv+7JkEn/Y4fyzkD3QUuht3E7LTnfxXA55w+NFRYz8eZEBzj8wSa8LXdnx3pePrjhpYDtH4HtdUY7xoG3OnY8aY9gX5qVp406SaSmFahBORZg6hXGG018NivOb5vDgZeoqFJvNgh1icA6hjqx+OGYZ91fiEzuFdLK0yYUJuqB8dOq2l7CQNrJUgtPoT8yAh+5VC4tzrCrqD/iX4skUR0d6lvr4GKB07GChULCHzAs8v8Hl0NApqRxJ1Pa4r2rKy/6A5L67MuHD37JQpqEK30W6XRHnCh0zUxOigwXWVLINPB+AbzMMW7MMnvW0pzpLVBledzNMkESoxdQN5EJkiCT8zSFRvWTbM6Vs34cGcSP0kwR2YjimfQrmMqknqTB/7U+elnmvO7tPDn1jA7dvx3ZmTVro9kQOkeSBgskH4/d9AQP5PawUPDGHKr2LghDZJpAMlTPM2Cas/+TQP8iVumIqc6B8zJ51yChYQoq7AXDGqyRr6EOXAmpcAjWkfgrUpvxM98Xrn5Wf5bmEEjE+Xnc/V74Bg=
      on:
        branch: main
        tags: true