language: python
python:
  - "3.7"

jobs:
  include:
    - stage: standalone
      name: "Code Style + Unit Tests (standalone)"
      before_install:
        - pip install pycodestyle
        - pip install pytest
        - pip install pytest-cov
        - pip install coveralls
      script:
        - find . -name \*.py -exec pycodestyle --exclude */res.py --max-line-length=120 --ignore=E402 {} +
        - pytest --cov=tpRigToolkit
      after_success:
        - coveralls
    - stage: docs
      name: "Build Documentation"
      if: tag =~ ^releases/*
      before_install:
        - pip install sphinx
        - pip install sphinx_rtd_theme
      script:
        - sphinx-apidoc -f -e -o docs/sphinx tpDcc
        - sphinx-build -M html ./docs/sphinx ./
      after_success:
        - cd html && touch .nojekyll && cd ../
      deploy:
        - provider: pages
          skip_cleanup: true
          github_token: "$GITHUB_TOKEN"
          keep_history: true
          local_dir: html
          on:
            branch: main
            tags: true
    - stage: deploy
      name: "Deploy"
      if: tag =~ ^releases/*
      script: skip
      deploy:
        - provider: pypi
          skip_cleanup: true
          user: tpoveda
          password:
            secure: PLEASE REPLACE ME
          on:
            branch: main
            tags: true
